language: scala
scala:
- 2.12.8
- 2.11.12
jdk:
- oraclejdk8
ignore:
- version.sbt
- README.md
sudo: false
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.coursier"
  - "$HOME/.sbt"
env:
  global:
  - PUBLISH=true
  - secure: GlL0F725rIzBkSDSmz8ZiW6ZaMi3JhB5nCRTDS8OeWyFEf4QWoSlbiU5RUdpUYsha/xHSbddWrzpKOxsEeTIqP07t69Mb5jdcv3eJAcGdP5xxuTMGIQJ3a3/zZZUgO26AhgLkmnaffp9PAJ0pNlAZ5FZWJbrlPV+hvvUOZk0uJi5qi2W1JQBZXEzvs364onlHCCXoBhw8GD4LLTY42FMxzKO8W9KN9SPYBoQtjQBeh5199AP+h5fMMj3eDp2IjAA/5h/PLIiihx5FYLgHtIWuRKPQeQel5Gu4TBVZTuhLWQJkf2f64EEhG66PlvwygSYlNJ8hMPxZSLCCC1IMEu9M+7lBYIqopZ9+iNHreGiWvzJ1k+fgcsUzQfzbrpOg2aDn1/S6EgH34EqCSoRtPCDqshwhMvritf1vIJn2eHxjdYzHUXaEIQyx8a3RlHvuXKJj9bOLSE/V+FhKhdrQXv3+HHdCi67QcjdrWRnn32l42BlsR85E5+DSafknWgP8JRyOnCWLWkIN9XxlN4AC4UhTmF1LXwZaENNvJjf4DTM/bvq1ko6Jq49VQrLTpAWnSpNrxxSXkoAIYAneSLiisrRvKzLzciQGu9t9uxkJjXBlTJbLXqda+IjZd1TOtekxzlnKgI1ZAiZxfeBxHimhYF45pAA9i0uGIujsLeVoOM=
  - secure: G9FwU8QblC+fII4GERJ7ItEVz9xBmfTOUyndyx34AgQSPj3Cto+oaAIi1eDuk/5fgOPK4CZ09aXcmzrdeKePXhOuGUQmxBkQpc0k6eQdZxfXYsytAdLU82wAploVaPTTLftISS5Qfd0x32EB75CZu6MXFENs+UQLePnQ8r756enwACIugGdDjzCjNXAUV6Cl8RAiadclGZ1vyxpQPOLnDfcKc6XDUS2XaUsuFez41rpjhx7Z1mfVNHu5Y+QgM4SOrMcX4qHIbMvm78w2oVFcdx6xVvfTtdpfhl2J5aIU8CebZCj+ov2Cc+t9dtwHLfOs09TMquxbVG+7eDzVFQu1MDGweF42ulCqd4hMgLogCgYr/dMSrNSzeMRtd6OPDos/fRbivfhaGn9dlGg+I3eqUZf2AlcrBT828NK3TFN/Oj35afG7BeOlBUT/6SbZfXPwh0IalRrDMegzbv9y91/N5g1BQ595tvQLQVOnTKaNKQj9kZso8nhTHcYEuz/WneNEV3+lbAi7TK9obalmlp+eC2UaCCUXNhr65cEpq2ljTgbTf/3udajZAOLInwUcuFFwlxe9o4jNJUcpeQF/PeOgZqHiuMLjCrPdOEMMb7jcV9dsUYFGIkm+XDyfTkSEijCcG09tD3za4GgyF74AI58kppMQJfTdsXxBOEoqnkZBgaQ=
  - secure: gDMPvfMvR5nk16c0GP/gBL8Ji9UYD3Uhm7bcXam0K1ZxpXMwkI/IZCGeT9USfHfu1mRlRHgxdqQ0ZeZ5Pz9UzCT3+HhUhzo7LQQLWR5YqedMAh6WntScEKefitoucIB3jr4yiOFQccxa5R4L+DT3GHnlHXx7faWOqUaGPKNVy5AlbjwXg1OuQRH0Kv3rlLoQzp/Kk8AcmWFuIvzCZvU5Kq/qCRN0Is2eaXZTzMwAjZHFcO8a2E6N3Pp+pYrc9KmJLfYJSRUXJ2n9TeVewHb3BVpLnmcaDgctOHWXr0bxPKuxaF+Tr389b2M8xMSlpauGS3d4+JR6y4HYr1gVnlvWoUHSQD+BGN7DhBH1MUeRkQPH2kxIMpsP6f3F1aqK/njI8R57PA785qnI5sgwHR06rYx+uM1xkSMryXz68LrAGlcloS0Ivn9TxCkHstSPzqbbsTwBnIkeXiCGU2fwPF13LjKBchyMUoMFJdCgvB/4/bERABkNy5vhtEqu5zkA49hZhWWPgL2VU+rq+ciVprnAZVS/FKWYStcVX4Vr3tYJ1m7acHGxk7TB+rYhNIUMBpdOPxIimk6mgtWLLcwTJ92NM6zPH6lI44t1640IU3Srx5qiIt6Z0uNzGGNlYLZziFEHLo/OOcV2L/oh773Xw2TnDH7xavVcmITFlPXw9ZxKNEE=
before_install:
- openssl aes-256-cbc -K $encrypted_577c46c2a89f_key -iv $encrypted_577c46c2a89f_iv
  -in ci.asc.enc -out local.ci.asc -d
before_script:
- gpg --import local.ci.asc
script:
- sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- git checkout $TRAVIS_BRANCH
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && sbt ++$TRAVIS_SCALA_VERSION
  'release with-defaults skip-tests'
